#!/bin/bash
# set -x
set -e
echo "Run as normal user (non-chroot-ed) "

JAIL='.'
echo $@

cp --parents "$(which $@)" "$JAIL"

for i in $(ldd $(which $@) | egrep -o '/lib.*\.[0-9]')
do
    echo $i
    cp --parents "$i" "$JAIL"
done

